<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.5.1 setup script
 * Date: Sat, 24 Oct 2015 15:50:01 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localserver [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'localserver';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'E9%eS&*puRbe';
$cfg['Servers'][$i]['ssl'] = false;

/* End of servers configuration */

$cfg['blowfish_secret'] = '562ba25ae708b5.62218276';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
